name: Pytest

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ${{ matrix.os-version }}
    continue-on-error: ${{ matrix.pre-release }}
    strategy:
      fail-fast: false
      matrix:
        os-version: ['ubuntu-latest']
        python-version: [3.9, '3.x']
        pre-release: [false]
        include:
          - os-version: 'ubuntu-20.04'
            python-version: 3.6
            pre-release: false
          - os-version: 'ubuntu-latest'
            python-version: '3.x-dev'
            pre-release: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: ${{ matrix.pre-release }}
        check-latest: ${{ matrix.pre-release }}
    - name: Install pytest and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Test with pytest
      run: |
        python -m pytest -vv tests/
